version: "3.9"
services:
  postgiss:
    container_name: postgiss
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=gis_database
    build: .
    volumes:
      - ../../DatosPG:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432
